SET storage_engine=InnoDB;
CREATE DATABASE IF NOT EXISTS PALESTRA;
USE PALESTRA; 
SET FOREIGN_KEY_CHECKS=1;
CREATE TABLE Istruttore(
CodF CHAR(20),
Nome CHAR(20) NOT NULL,
Cognome CHAR(20) NOT NULL,
DataNascita DATE NOT NULL,
Email CHAR(50),
Telefono CHAR(15) NULL,
PRIMARY KEY (CodF)
);

CREATE TABLE Corsi(
CodC CHAR(5),
Nome CHAR(20) NOT NULL,
Tipo CHAR(10) NOT NULL,
Livello SMALLINT NOT NULL
PRIMARY KEY (Codc),
CONSTRAINT chk_Livello CHECK (Livello>=1 and LIVELLO <=4)
);

CREATE TABLE Programma(
CodF CHAR(20) NOT NULL,
Giorno CHAR(10) NOT NULL,
OraInizio HOUR NOT NULL,
Durata INT NOT NULL,
CodC CHAR(5) NOT NULL,
Sala CHAR(2) NOT NULL,
PRIMARY KEY (CodF,Giorno,OraInizio),
FOREIGN KEY (CodF)
REFERENCES Istruttore(CodF)
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY (CodC)
REFERENCES Corsi(CodC)
ON DELETE CASCADE
ON UPDATE CASCADE
);



